name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install --no-install-recommends -qq -y \
            bindfs \
            black \
            clang \
            clang-tools \
            clang-format \
            dbus \
            desktop-file-utils \
            elfutils \
            findutils \
            flake8 \
            fuse \
            gcc \
            gdb \
            g++ \
            gettext \
            gi-docgen \
            git \
            libc6-dev \
            gobject-introspection \
            gtk-doc-tools \
            itstool \
            lcov \
            libattr1-dev \
            libdbus-1-dev \
            libelf-dev \
            libffi-dev \
            libgirepository1.0-dev \
            libmount-dev \
            libpcre2-dev \
            libselinux1-dev \
            libxml2-utils \
            libxslt1-dev \
            libz3-dev \
            locales \
            ninja-build \
            python3 \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            reuse \
            shared-mime-info \
            shellcheck \
            systemtap-sdt-dev \
            unzip \
            wget \
            xsltproc \
            xz-utils \
            zlib1g-dev
          sudo rm -rf /usr/share/doc/* /usr/share/man/*
      - name: Generate locales for build
        run: |
          sudo locale-gen C.UTF-8
          sudo /usr/sbin/update-locale LANG=C.UTF-8
      - name: Generate locales for tests
        run: |
          sudo locale-gen de_DE.UTF-8
          sudo locale-gen el_GR.UTF-8
          sudo locale-gen en_US.UTF-8
          sudo locale-gen es_ES.UTF-8
          sudo locale-gen fa_IR.UTF-8
          sudo locale-gen fr_FR.UTF-8
          sudo locale-gen hr_HR.UTF-8
          sudo locale-gen ja_JP.UTF-8
          sudo locale-gen lt_LT.UTF-8
          sudo locale-gen pl_PL.UTF-8
          sudo locale-gen ru_RU.UTF-8
          sudo locale-gen th_TH.UTF-8
          sudo locale-gen tr_TR.UTF-8
      - name: Set locale environment variables
        run: |
          echo "LANG=C.UTF-8" | sudo tee -a /etc/environment
          echo "LANGUAGE=C.UTF-8" | sudo tee -a /etc/environment
          echo "LC_ALL=C.UTF-8" | sudo tee -a /etc/environment
      - name: Install meson
        run: |
          sudo pip3 install meson==1.4.2
      - name: Prepare subprojects
        run: |
          git submodule update --init
          meson subprojects download --sourcedir .

      - name: Set CFLAGS and CXXFLAGS
        run: |
          echo "CFLAGS=--coverage -ftest-coverage -fprofile-arcs -fprofile-update=atomic" | sudo tee -a /etc/environment
          echo "CXXFLAGS=--coverage -ftest-coverage -fprofile-arcs -fprofile-update=atomic" | sudo tee -a /etc/environment

      - name: Build
        run: |
          meson setup --buildtype debug  \
          --wrap-mode=nodownload  \
          --fatal-meson-warnings  \
          --werror  \
          --default-library=both  \
          --prefix=$GITHUB_WORKSPACE/glib-installed  \
          --localstatedir=/var  \
          --libdir=lib  \
          -Dsystemtap=enabled  \
          -Ddtrace=enabled  \
          -Dinstalled_tests=true  \
          -Ddocumentation=true  \
          -Dintrospection=enabled  \
          -Dman-pages=enabled  \
          _build

      - name: Compile
        run: |
          meson compile -C _build

      - name: Create coverage directory
        run: |
          mkdir -p _coverage

      - name: Run tests
        run: |
          .gitlab-ci/run-tests.sh

      - name: Create reference directory
        run: |
          mkdir -p _reference/

      - name: Move reference files
        run: |
          mv _build/docs/reference/glib/glib-2.0/ _reference/glib/
          mv _build/docs/reference/glib/glib-unix-2.0/ _reference/glib-unix/
          mv _build/docs/reference/gmodule/gmodule-2.0/ _reference/gmodule/
          mv _build/docs/reference/gobject/gobject-2.0/ _reference/gobject/
          mv _build/docs/reference/gio/gio-2.0/ _reference/gio/
          mv _build/docs/reference/gio/gio-unix-2.0/ _reference/gio-unix/
          mv _build/docs/reference/girepository/girepository-2.0/ _reference/girepository/